# Generated by Django 3.1.7 on 2021-10-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='classgroup',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
