# Generated by Django 3.1.7 on 2021-10-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0002_listing_classgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='classgroup',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
